linters:
  enable-all: true
  disable:
    - execinquery
    - exhaustruct
    - exhaustivestruct
    - golint
    - interfacer
    - ireturn
    - maligned
    - paralleltest
    - scopelint
    - varnamelen

issues:
  exclude-use-default: false

linters-settings:
  gomnd:
    settings:
      mnd:
        ignored-numbers: "2"
  govet:
    check-shadowing: true
