version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    - mage
    - go generate ./...
    - go mod tidy
    - go mod download

builds:
  - id: jwt-auth-registry
    main: ./cmd/jwt-auth-registry
    binary: jwt-auth-registry
    flags:
      - -tags=release
      - -buildmode=default
      - -trimpath
      - -v
    ldflags:
      - "-X github.com/dosquad/go-cliversion.BuildDate={{ .Date }}"
      - "-X github.com/dosquad/go-cliversion.BuildDebug=false"
      - "-X github.com/dosquad/go-cliversion.BuildMethod=goreleaser"
      - "-X github.com/dosquad/go-cliversion.BuildVersion={{.Version}}"
      - "-X github.com/dosquad/go-cliversion.GitCommit={{.ShortCommit}}"
      - '-X github.com/dosquad/go-cliversion.GitRepo={{.GitURL}}'
      - '-X github.com/dosquad/go-cliversion.GitSlug={{- $gitsa := split (trimsuffix .GitURL ".git") ":" -}}{{- $gitsp := split (index $gitsa 1) "/" -}}{{- $size := len $gitsp -}}{{- $sla := len (slice (printf "%*s" $size "") 2) -}}{{ $slb := len (slice (printf "%*s" $size "") 1) -}}{{index $gitsp $sla}}/{{index $gitsp $slb}}'
      - "-X github.com/dosquad/go-cliversion.GitTag={{.Version}}"
      - "-X github.com/dosquad/go-cliversion.GitExactTag={{.RawVersion}}"
      - "-X main.commit={{.ShortCommit}}"
      - "-X main.date={{ .Date }}"
      - "-X main.builtBy=goreleaser"
      - "-X main.repo={{.GitURL}}"
      - "-X main.goVersion=1.22.4"
      - "-X main.version={{.Version}}"
      - "-s"
      - "-w"
    mod_timestamp: '{{ .CommitTimestamp }}'
    goarm: [ '5', '6', '7' ]
    goos: ['linux', 'darwin', 'windows']
    goarch: ['amd64', 'arm', 'arm64']
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - allow_different_binary_count: true

checksum:
  algorithm: sha256
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - ids:
      - jwt-auth-registry
    dockerfile: Dockerfile.goreleaser
    image_templates:
    - "ghcr.io/na4ma4/jwt-auth-registry:{{ .Tag }}"
    - "ghcr.io/na4ma4/jwt-auth-registry:{{ .Major }}"
    - "ghcr.io/na4ma4/jwt-auth-registry:latest"
    extra_files:
    - "scripts/replace-links-in-ssl-certs.sh"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"

nfpms:
  -
    id: jwt-auth-registry
    package_name: jwt-auth-registry
    file_name_template: "jwt-auth-registry_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    builds:
      - jwt-auth-registry
    homepage: https://github.com/na4ma4/jwt-auth-registry
    maintainer: na4ma4 <na4ma4@users.noreply.github.com>
    description: JWT-based Authentication Proxy
    formats:
      - apk
      - deb
    bindir: /usr/bin
    contents:
      - src: "systemd/jwt-auth-registry.service"
        dst: "/lib/systemd/system/jwt-auth-registry.service"
    overrides:
      deb:
        scripts:
          preinstall: "nfpms/pre-install.sh"
          postinstall: "nfpms/post-install.sh"
          preremove: "nfpms/pre-remove.sh"
          postremove: "nfpms/post-remove.sh"
